/**
 * lib/brief.ts — TECH-SPEC §8's BRIEF_PROMPT/PLAN_PROMPT calling code (haiku, via the proxy).
 *
 * Kept separate from lib/agent.ts (the per-turn streamText loop) and lib/com.ts (the
 * independent scorer, which imports nothing from here or agent.ts) — this is a third,
 * independent structured-generation path triggered ONCE per extraction, not per chat turn.
 * Never throws across its entry point — failures surface as a chat error block, same
 * throw-safety discipline as lib/tools.ts.
 */

import { createAnthropic } from "@ai-sdk/anthropic";
import { generateObject, streamObject } from "ai";
import { nanoid } from "nanoid";
import {
  briefLlmSchema,
  buildBriefPrompt,
  buildPlanPrompt,
  planLlmSchema,
} from "./prompts";
import { useChatStore, useExperimentsStore, useSchemaStore, useSessionStore } from "./store";
import type { Experiment, PageBrief } from "./types";

// Same proxy pattern as lib/agent.ts — the key never reaches the browser (TECH-SPEC §1).
const anthropic = createAnthropic({ apiKey: "proxied", baseURL: "/api/anthropic/v1" });

function emptyBrief(seo: PageBrief["seo"], a11yAudit: PageBrief["a11yAudit"]): PageBrief {
  return {
    seo,
    icp: "",
    problemStatement: "",
    valueProp: "",
    painPoints: { addressed: [], missed: [] },
    objections: { handled: [], unhandled: [] },
    proofAudit: { present: [], missing: [] },
    ctaAudit: [],
    a11yAudit, // deterministic — never regenerated by the LLM (TECH-SPEC §6)
    segments: [],
    suggestedGoals: [],
    tone: "",
    lang: "",
  };
}

/**
 * Kicks off brief generation (streamObject — fields fill progressively, satisfying the
 * TECH-SPEC §10 "brief streams" latency choreography) then, once it lands, the Experiment
 * Plan (generateObject, runs after the brief per TECH-SPEC §8). Fire-and-forget from the
 * extraction handler in app/page.tsx — never rejects.
 */
export async function runBriefAndPlan(): Promise<void> {
  const chat = useChatStore.getState();
  const schema = useSchemaStore.getState();
  const session = useSessionStore.getState();

  if (schema.order.length === 0) return; // nothing extracted — nothing to brief

  chat.pushBrief();
  // a11yAudit + the raw SEO record are deterministic — seed them BEFORE the LLM call even
  // starts, so the artifact shows real, grounded content with zero dead air; the rest of the
  // fields fill in as streamObject's partials arrive.
  session.setBrief(emptyBrief(schema.seo ?? { title: "", og: {}, headingOutline: [] }, schema.a11yAudit));

  const slots: { path: string; type: string; text: string }[] = [];
  for (const id of schema.order) {
    const node = schema.nodes[id];
    for (const [slotName, slot] of Object.entries(node.slots)) {
      if (slot.text) slots.push({ path: `${node.path}.${slotName}`, type: node.type, text: slot.text });
    }
  }

  try {
    const result = streamObject({
      model: anthropic("claude-haiku-4-5"),
      schema: briefLlmSchema,
      prompt: buildBriefPrompt({ url: session.url, seo: schema.seo, slots }),
    });

    for await (const partial of result.partialObjectStream) {
      // Each partial is the FULL object accumulated so far (not a diff) — a shallow merge
      // over the a11yAudit-seeded brief is correct and keeps a11yAudit untouched (excluded
      // from the LLM schema entirely).
      useSessionStore.getState().patchBrief(partial as unknown as Partial<PageBrief>);
    }

    const finalObj = await result.object;
    // Ground ctaAudit paths app-side (same discipline as runPlan's targetPath validation,
    // TECH-SPEC §8): the LLM composes these freely and can cite a slot-suffixed or invented
    // path. Keep real node paths as-is; normalize a "node.slot" reference to its real node
    // path; drop anything that traces to no extracted component — no invented claims survive.
    const validPaths = new Set(useSchemaStore.getState().outline().map((o) => o.path));
    const groundedCtaAudit = finalObj.ctaAudit
      .map((c) => {
        if (validPaths.has(c.path)) return c;
        const nodePath = c.path.slice(0, c.path.lastIndexOf("."));
        return nodePath && validPaths.has(nodePath) ? { ...c, path: nodePath } : null;
      })
      .filter((c): c is NonNullable<typeof c> => c !== null);
    const finalBrief: PageBrief = { ...finalObj, ctaAudit: groundedCtaAudit, a11yAudit: schema.a11yAudit };
    useSessionStore.getState().setBrief(finalBrief);

    // Default goal = first suggestion, unless the user already picked one (TECH-SPEC §10).
    if (!useSessionStore.getState().goal && finalBrief.suggestedGoals[0]) {
      useSessionStore.getState().setGoal(finalBrief.suggestedGoals[0]);
    }

    await runPlan(finalBrief);
  } catch (e) {
    useChatStore.getState().pushError(`brief generation failed: ${e instanceof Error ? e.message : String(e)}`);
  }
}

type ProposalRaw = { name: string; targetPath: string; hypothesis: string };

/** generateObject → validate targetPaths app-side → one re-run (listing dropped names) if
 *  fewer than 6 survive → populate the experiments store. Every surviving proposal's
 *  targetPath is guaranteed to exist in the schema outline (TECH-SPEC §8). */
async function runPlan(brief: PageBrief, prior: ProposalRaw[] = [], invalidPaths?: string[]): Promise<void> {
  const schema = useSchemaStore.getState();
  const outline = schema.outline().map((o) => ({ path: o.path, type: o.type, preview: o.preview }));
  const validPaths = new Set(outline.map((o) => o.path));

  if (!invalidPaths) useChatStore.getState().pushPlan();

  const { object } = await generateObject({
    model: anthropic("claude-haiku-4-5"),
    schema: planLlmSchema,
    prompt: buildPlanPrompt({ brief, outline, invalidPaths }),
  });

  const survivors = [...prior, ...object.experiments.filter((e) => validPaths.has(e.targetPath))];
  const dropped = object.experiments.filter((e) => !validPaths.has(e.targetPath)).map((e) => e.targetPath);

  if (survivors.length < 6 && !invalidPaths) {
    return runPlan(brief, survivors, dropped.length > 0 ? dropped : ["(none — model just under-proposed)"]);
  }

  const experiments: Experiment[] = survivors.map((e) => ({
    id: nanoid(),
    name: e.name,
    targetPath: e.targetPath,
    hypothesis: e.hypothesis,
    status: "proposed",
    armIds: [],
  }));
  useExperimentsStore.getState().setList(experiments);
}
