/**
 * scripts/build-runtime.mjs
 * Bundles lib/runtime.ts to an IIFE string written to lib/runtime.built.js.
 * Run as `predev` and `prebuild` in package.json.
 */
import { build } from "esbuild";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

const result = await build({
  entryPoints: [join(root, "lib", "runtime.ts")],
  bundle: true,
  format: "iife",
  platform: "browser",
  target: "es2020",
  minify: false,
  write: false,
});

const code = new TextDecoder().decode(result.outputFiles[0].contents);

// Write as a JS module that exports the string
const output = `// AUTO-GENERATED by scripts/build-runtime.mjs — do not edit
// eslint-disable-next-line
const runtimeCode = ${JSON.stringify(code)};
export default runtimeCode;
`;

writeFileSync(join(root, "lib", "runtime.built.js"), output, "utf-8");
console.log("[build-runtime] lib/runtime.built.js written (" + code.length + " chars)");
